# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Markdown flavoured')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
