# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 05:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 (largest) to 4 (smallest)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
