# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='font_size',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Large'), (2, 'Medium'), (3, 'Small'), (4, 'Extra Small')], default=1),
        ),
    ]
