# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 11:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0010_auto_20180306_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='4 = Must have!, 3 = Interesting talk, 2 = Meh, 1 = Definitely not!, blank value = No score (f.e. your proposal) ', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
