# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0013_auto_20180306_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='is_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='is_keynote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workshop',
            name='is_backup',
            field=models.BooleanField(default=False),
        ),
    ]
