# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', help_text='will be markdowned', max_length=100)),
                ('room', models.PositiveSmallIntegerField(choices=[(1, 'Main'), (2, 'Theatre'), (4, 'room 301'), (5, 'room 302'), (6, 'room 303'), (7, 'room 343'), (8, 'room 346'), (9, 'room 347'), (10, 'room 348'), (11, 'room 349'), (20, 'Respirium'), (30, 'Foyer'), (40, 'Backyard'), (50, 'Red room'), (60, 'Fish tank')])),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('date', 'room'),
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('short_bio', models.TextField(blank=True, help_text='For keynote speakers', verbose_name='Short bio')),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='programme/pyconcz2018/')),
                ('display_position', models.PositiveSmallIntegerField(default=0, help_text='sort order on frontend displays')),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_position', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English (preferred)'), ('cs', 'Czechoslovak')], default='en', max_length=2)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', max_length=10)),
                ('video_id', models.CharField(blank=True, default='', help_text='youtube', max_length=100)),
                ('private_note', models.TextField(blank=True, default='', help_text='DO NOT SHOW ON WEBSITE')),
                ('is_backup', models.BooleanField(default=False)),
                ('is_keynote', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('workshop', 'Workshop'), ('sprint', 'Sprint')], default='sprint', max_length=10)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('abstract', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English (preferred)'), ('cs', 'Czech/Slovak')], default='en', max_length=2)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced')], default='beginner', max_length=10)),
                ('length', models.CharField(blank=True, choices=[('1h', '1 hour'), ('2h', '2 hours'), ('2h', '3 hours'), ('1d', 'Full day (most sprints go here!)'), ('xx', 'Something else! (Please leave a note in the abstract!)')], max_length=2)),
                ('private_note', models.TextField(blank=True, default='', help_text='DO NOT SHOW ON WEBSITE')),
                ('is_backup', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('registration', models.CharField(blank='free', choices=[('without', 'Without'), ('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='talks',
            field=models.ManyToManyField(blank=True, related_name='talk_speakers', to='programme.Talk'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='ws_speakers', to='programme.Workshop'),
        ),
    ]
