# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_auto_20190320_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(upload_to='programme/speakers/'),
        ),
    ]
