# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_auto_20190407_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='attendee_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=False, verbose_name='Maximum number of attendees allowed'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='requirements',
            field=models.TextField(blank=True, default='', help_text='Include even the most obvious stuff: laptops, git, python', verbose_name='What should attendees bring, install and know?'),
        ),
    ]
