# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-14 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_auto_20190409_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='og_image',
            field=models.ImageField(blank=True, default=False, help_text='og:image (social media image) 1200×630 pixels', upload_to='programme/talks/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='og_image',
            field=models.ImageField(blank=True, default=False, help_text='og:image (social media image) 1200×630 pixels', upload_to='programme/workshops/'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='in_data_track',
            field=models.BooleanField(default=False, verbose_name='PyData Track'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='attendee_limit',
            field=models.PositiveSmallIntegerField(blank=True, default=False, help_text='Maximum number of attendees allowed', verbose_name='Atendee limit'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='in_data_track',
            field=models.BooleanField(default=False, verbose_name='PyData Track'),
        ),
    ]
