# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-15 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_auto_20190414_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='og_image',
            field=models.ImageField(blank=True, help_text='og:image (social media image) 1200×630 pixels', null=True, upload_to='programme/talks/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='og_image',
            field=models.ImageField(blank=True, help_text='og:image (social media image) 1200×630 pixels', null=True, upload_to='programme/workshops/'),
        ),
    ]
