# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0008_workshop_tito_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ball room'), (2, 'Club'), (4, 'room EB126'), (5, 'room EB129'), (6, 'room EB130'), (7, 'room EB226'), (8, 'room EB229'), (9, 'room EB230'), (30, 'Foyer'), (40, 'Compress hall'), (50, 'Gallery')]),
        ),
    ]
