# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0009_auto_20190508_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='talk',
            name='order',
            field=models.SmallIntegerField(default=100, help_text='display order on front end, has to be unique'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='order',
            field=models.SmallIntegerField(default=100, help_text='display order on front end, has to be unique'),
        ),
    ]
