# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0010_auto_20190508_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='order',
            field=models.SmallIntegerField(help_text='display order on front end, has to be unique', unique=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='order',
            field=models.SmallIntegerField(help_text='display order on front end, has to be unique', unique=True),
        ),
    ]
