# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0012_utility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ('start', 'room')},
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='slot',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
