# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-15 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0016_utility_is_streamed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utility',
            options={'ordering': ('title', 'id'), 'verbose_name': 'Utility', 'verbose_name_plural': 'Utilities'},
        ),
        migrations.RemoveField(
            model_name='slot',
            name='description',
        ),
        migrations.AlterField(
            model_name='utility',
            name='is_streamed',
            field=models.BooleanField(default=False, verbose_name='Is streamed to other rooms'),
        ),
    ]
