# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_auto_20180306_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Platinum'), (2, 'Gold'), (3, 'Silver'), (4, 'Bronze'), (5, 'Diversity'), (6, 'Media'), (7, 'Partners'), (8, 'Coffee sponsor'), (9, 'Connectivity sponsor'), (10, 'Tea sponsor')], default=3),
        ),
    ]
