# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='facebook',
            field=models.URLField(help_text='full URL', null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='twitter',
            field=models.URLField(help_text='full URL', null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Platinum'), (2, 'Gold'), (3, 'Silver'), (4, 'Bronze'), (5, 'Diversity'), (6, 'Media'), (7, 'Partners'), (8, 'Coffee sponsor'), (9, 'Connectivity sponsor')], default=3),
        ),
    ]
