# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, help_text='Markdown formatted', null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.FileField(blank=True, help_text='should be SVG', null=True, upload_to='sponsors/pyconcz/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
