# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-15 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0004_auto_20180306_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Platinum'), (2, 'Gold'), (3, 'Silver'), (4, 'Bronze'), (5, 'Diversity'), (6, 'Media'), (7, 'Partners'), (8, 'Coffee sponsor'), (9, 'Con\xadnectiv\xadity sponsor'), (10, 'Tea sponsor')], default=3),
        ),
    ]
