# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0005_auto_20180416_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Platinum'), (2, 'Gold'), (3, 'Silver'), (4, 'Bronze'), (5, 'Diversity'), (6, 'Media'), (7, 'Partners'), (9, 'Con\xadnectiv\xadity')], default=3),
        ),
    ]
