# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('room', models.PositiveSmallIntegerField(choices=[(1, 'Main'), (2, 'Theatre'), (4, 'room 346'), (
                    5, 'room 347'), (6, 'room 301'), (7, 'room 302'), (8, 'room 303'), (9, 'room 343'), (3, 'Foyer')])),
                ('content_type', models.ForeignKey(blank=True, null=True,
                                                   on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('date', 'room'),
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('keynote', models.BooleanField(default=False)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='programme/pyconcz2018/')),
                ('display_position', models.PositiveSmallIntegerField(
                    default=0, help_text='sort order on frontend displays')),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('display_position', 'full_name'),
            },
        ),
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('language', models.CharField(choices=[
                 ('en', 'English (preferred)'), ('cs', 'Czechoslovak')], default='en', max_length=2)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'),
                                                         ('advanced', 'Advanced')], default='beginner', max_length=10)),
                ('video_id', models.CharField(blank=True, default='', help_text='youtube', max_length=100)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('workshop', 'Workshop'),
                                                   ('sprint', 'Sprint')], default='sprint', max_length=10)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('abstract', models.TextField()),
                ('language', models.CharField(choices=[
                 ('en', 'English (preferred)'), ('cs', 'Czech/Slovak')], default='en', max_length=2)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'),
                                                         ('advanced', 'Advanced')], default='beginner', max_length=10)),
                ('length', models.CharField(blank=True, choices=[('1h', '1 hour'), ('2h', '2 hours'), ('2h', '3 hours'), (
                    '1d', 'Full day (most sprints go here!)'), ('xx', 'Something else! (Please leave a note in the abstract!)')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='speaker',
            name='talks',
            field=models.ManyToManyField(blank=True, related_name='talks', to='programme.Talk'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='workshops', to='programme.Workshop'),
        ),
    ]
