# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='keynote',
        ),
        migrations.AddField(
            model_name='talk',
            name='is_backup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='is_keynote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='talk',
            name='private_note',
            field=models.TextField(blank=True, default='', help_text='DO NOT SHOW ON WEBSITE'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='talks',
            field=models.ManyToManyField(blank=True, related_name='talk_speakers', to='programme.Talk'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='ws_speakers', to='programme.Workshop'),
        ),
    ]
