# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_speaker_short_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='description',
            field=models.CharField(blank=True, default='', help_text='will be markdowned', max_length=100),
        ),
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Main'), (2, 'Theatre'), (4, 'room 346'), (5, 'room 347'), (6, 'room 301'), (7, 'room 302'), (8, 'room 303'), (9, 'room 343'), (30, 'Foyer'), (40, 'Backyard')]),
        ),
    ]
