# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-19 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0007_auto_20180519_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Main'), (2, 'Theatre'), (4, 'room 301'), (5, 'room 302'), (6, 'room 303'), (7, 'room 343'), (8, 'room 346'), (9, 'room 347'), (10, 'room 348'), (11, 'room 349'), (20, 'Respirium'), (30, 'Foyer'), (40, 'Backyard'), (50, 'Red room'), (60, 'Fish tank')]),
        ),
    ]
