# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0010_auto_20180522_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='registration',
            field=models.CharField(blank='free', choices=[('without', 'Without'), ('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
    ]
