# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 17:54
from datetime import datetime

from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc

from pyconcz.common.models import Phase, PhaseValue


def create_initial_flag(apps, schema_editor):
    for flag_name, value_names in {
        'date': ['unknown', 'announced'],
        'city': ['unknown', 'announced'],
        'venue': ['unknown', 'announced'],
        'sales_early': ['not_launched', 'opened', 'sold_out', 'timed_out'],
        'sales_standard': ['not_launched', 'opened', 'sold_out', 'timed_out'],
        'sales_late': ['not_launched', 'opened', 'sold_out', 'timed_out'],
        'schedule': ['not_public', 'published'],
        'city_info': ['not_public', 'published'],
        'board_games': ['not_public', 'opened', 'sold_out', 'timed_out'],
        'streams': ['not_public', 'live', 'some_past', 'all_past', 'hidden'],
        'videos': ['non_existent', 'not_public', 'public'],
    }.items():
        flag, new = Phase.objects.get_or_create(name=flag_name)
        if new:
            flag.save()
        for i, value_name in enumerate(value_names):
            value, new = PhaseValue.objects.get_or_create(
                phase=flag, name=value_name, enabled=True)
            if new:
                if i:
                    # Put in fake datetimes to order the phases properly
                    value.active_since = datetime(9999, 1, 1, 0, 0, i, tzinfo=utc)
                value.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PhaseValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('active_since', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='common.Phase')),
            ],
            options={
                'ordering': ('phase__name', 'enabled', 'active_since', 'name'),
            },
        ),
        migrations.AddField(
            model_name='phase',
            name='override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.PhaseValue'),
        ),
        migrations.AlterUniqueTogether(
            name='phasevalue',
            unique_together=set([('phase', 'name')]),
        ),
        migrations.RunPython(
            create_initial_flag,
            migrations.RunPython.noop,
        ),
    ]
