# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 17:18
from __future__ import unicode_literals

from django.db import migrations, models

from pyconcz.common.models import SiteFlag


def create_initial_flag(apps, schema_editor):
    SiteFlag(name='schedule_published', value_type='off').save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value_type', models.CharField(choices=[('on', 'on'), ('off', 'off'), ('on_at', 'on_at'), ('off_at', 'off_at')], max_length=200)),
                ('switch_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(
            create_initial_flag,
            migrations.RunPython.noop,
        ),
    ]
