# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasevalue',
            options={'ordering': ('phase__name', 'active_since', 'name')},
        ),
        migrations.AlterField(
            model_name='phase',
            name='override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overriden_in', to='common.PhaseValue'),
        ),
    ]
