# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20180116_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='finaid_details',
            field=models.TextField(blank=True, help_text='Describe what you need from us.', null=True, verbose_name='Financial aid details'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='needs_finaid',
            field=models.BooleanField(default=False, help_text='Do you need financial help from us? | Covering travel or accommodation costs etc.', verbose_name='I need financial help'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='finaid_details',
            field=models.TextField(blank=True, help_text='Describe what you need from us.', null=True, verbose_name='Financial aid details'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='needs_finaid',
            field=models.BooleanField(default=False, help_text='Do you need financial help from us? | Covering travel or accommodation costs etc.', verbose_name='I need financial help'),
        ),
    ]
