# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-21 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0002_auto_20190121_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='github',
            field=models.URLField(blank=True, default='', help_text='Optional. The whole URL.', verbose_name='Your public code repository (GitHub, GitLab, …)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='github',
            field=models.URLField(blank=True, default='', help_text='Optional. The whole URL.', verbose_name='Your public code repository (GitHub, GitLab, …)'),
        ),
    ]
