# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0003_auto_20180116_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='photo',
            field=models.ImageField(help_text=' Photo of yourself which we can publish on our website. Please use a square photo of minimum size 600 by 600 px.', upload_to='proposals/pyconcz2018/talks/', verbose_name='Your picture'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='photo',
            field=models.ImageField(help_text='Photo of yourself which we can publish on our website. Please use a square photo of minimum size 600 by 600 px.', upload_to='proposals/pyconcz2018/talks/', verbose_name='Your picture'),
        ),
    ]
