# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-21 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0004_auto_20190121_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='gdpr_consent',
            field=models.BooleanField(default=False, help_text='<a href="/2019/about/privacy/">Privacy Policy</a> and <a href="/2019/about/code/">Code of Conduct</a>', verbose_name='I have read and agree to the PyCon CZ Privacy Policy and Code of Conduct'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='gdpr_consent',
            field=models.BooleanField(default=False, help_text='<a href="/2019/about/privacy/">Privacy Policy</a> and <a href="/2019/about/code/">Code of Conduct</a>', verbose_name='I have read and agree to the PyCon CZ Privacy Policy and Code of Conduct'),
        ),
    ]
