# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-31 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0005_auto_20190121_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaid',
            name='gdpr_consent',
            field=models.BooleanField(default=False, help_text='<a href="/2019/about/privacy/">Privacy Policy</a> and <a href="/2019/about/code/">Code of Conduct</a>', verbose_name='I have read and agree to the PyCon CZ Privacy Policy and Code of Conduct'),
        ),
    ]
