# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-11 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0006_financialaid_gdpr_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='amount',
            field=models.CharField(help_text='If you require just a free ticket, please state “ticket”.\nPlease use following conversion rates: 1 Euro = 25 Czech Korunas = $1.13', max_length=255, verbose_name='How much total money would you like to receive (in Euros)'),
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='purpose',
            field=models.TextField(help_text='If you require help for more items (accomodation, travel costs etc.) please state the amount for each of them in Euros.\nYou don’t need to specify the price of a ticket.\nPlease use following conversion rates: 1 Euro = 25 Czech Korunas = $1.13', verbose_name='What do you need the money for exactly?'),
        ),
    ]
