# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0007_auto_20190211_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaid',
            name='purpose',
            field=models.TextField(help_text='If you require help for more items (accomodation, travel costs etc.) please state the amount for each of them in Euros separately.\nKeep in mind that financial aid can’t cover your food costs.\nYou don’t need to specify the price of a ticket.\nPlease use following conversion rates: 1 Euro = 25 Czech Korunas = $1.13', verbose_name='What do you need the money for exactly?'),
        ),
    ]
