# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_auto_20180124_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='bio',
            field=models.TextField(help_text='Tell your audience in first person about anything relevant about you, whether it’s your background, education, experience, current or former employer, hobbies or opensource software you maintain.\nTry keeping it between between 50 and 90 words.\nYou can of course include anything fun or quirky about yourself.', verbose_name='Why are you the right person to talk about the topic you chose?'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='bio',
            field=models.TextField(help_text='Tell your audience in first person about anything relevant about you, whether it’s your background, education, experience, current or former employer, hobbies or opensource software you maintain.\nTry keeping it between between 50 and 90 words.\nYou can of course include anything fun or quirky about yourself.', verbose_name='Why are you the right person to talk about the topic you chose?'),
        ),
    ]
