# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0008_auto_20190225_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='photo',
            field=models.ImageField(help_text='If you don’t have a photo according to specs below, we will ask you for one if your talk is selected.\nIdeal photo is:\n– as large as possible (please no 128 × 128 px, there is no upper limit, even 1000 × 1000 px isn’t too much),\n– as uncompressed as possible (JPEGs are ok),\n– doesn’t show other people\n– is a head shot (not you in front of a pyramid)\n– is not black and white and has no “creative filters” applied.\nWe might crop it and change contrast, brightness etc. to fit PyCon CZ visual style.', upload_to='proposals/pyconcz2019/talks/', verbose_name='Your photo (not an\xa0illustration nor\xa0avatar)'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='photo',
            field=models.ImageField(help_text='If you don’t have a photo according to specs below, we will ask you for one if your workshop is selected.\nIdeal photo is:\n– as large as possible (please no 128 × 128 px, there is no upper limit, even 1000 × 1000 px isn’t too much),\n– as uncompressed as possible (JPEGs are ok),\n– doesn’t show other people\n– is a head shot (not you in front of a pyramid)\n– is not black and white and has no “creative filters” applied.\nWe might crop it and change contrast, brightness etc. to fit PyCon CZ visual style.', upload_to='proposals/pyconcz2019/talks/', verbose_name='Your photo (not an\xa0illustration nor\xa0avatar)'),
        ),
    ]
