# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_auto_20190312_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='length',
            field=models.CharField(blank=True, choices=[('1h', '1 hour'), ('2h', '2 hours'), ('3h', '3 hours'), ('1d', 'Full day (most sprints go here!)'), ('xx', 'Something else! (Please leave a note in the abstract)')], help_text='Sprints usually take the whole day, but workshops are organized in smaller blocks. You can also have a full-day workshop with lunch break, but keep in mind that the length could discourage attendees.', max_length=2, verbose_name='How much time does your workshop take?'),
        ),
    ]
