# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 11:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0009_auto_20180205_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.PositiveSmallIntegerField(blank=True, help_text='4 = Must have!, 3 = Interesting talk, 2 = Meh, 1 = Definitely not!, blank value = No score (f.e. your proposal) ', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
