# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-14 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0014_auto_20180314_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialaid',
            name='bio',
        ),
        migrations.AddField(
            model_name='financialaid',
            name='community_involvement',
            field=models.TextField(blank=True, help_text='It’s a plus but we don’t limit Financial Aid to those who do.', null=True, verbose_name='Do you contribute or plan to contribute to Python community in any way? (optional)'),
        ),
        migrations.AddField(
            model_name='financialaid',
            name='python_involvement',
            field=models.CharField(help_text='e.g. You’re learning it or teaching it or using for something…', max_length=400, null=True, verbose_name='What is your connection with Python?'),
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='amount',
            field=models.CharField(help_text='If you require just a free ticket, please state “ticket”.\nPlease use following conversion rates: 1 Euro = 25 Czech Korunas = $1.23', max_length=255, verbose_name='How much total money would you like to receive (in Euros)'),
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='email',
            field=models.EmailField(help_text='We’ll send information about your application result to this address.', max_length=254, verbose_name='Your email address'),
        ),
        migrations.AlterField(
            model_name='financialaid',
            name='purpose',
            field=models.TextField(help_text='If you require help for more items (accomodation, travel costs etc.) please state the amount for each of them in Euros.\nYou don’t need to specify the price of a ticket.\nPlease use following conversion rates: 1 Euro = 25 Czech Korunas = $1.23', verbose_name='What do you need the money for exactly?'),
        ),
    ]
