# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='photo',
            field=models.ImageField(upload_to='team/'),
        ),
    ]
