# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_auto_20180319_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='short_bio',
            field=models.TextField(blank=True, help_text='For keynote speakers', verbose_name='Short bio'),
        ),
    ]
