# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0009_workshop_requires_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='requires_registration',
        ),
        migrations.AddField(
            model_name='workshop',
            name='registration',
            field=models.CharField(blank='free', choices=[('none', 'Without registration'), ('free', 'Free registration'), ('paid', 'Paid registration')], default='free', max_length=10),
        ),
    ]
