# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-24 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', help_text='This is private', max_length=254)),
                ('twitter', models.CharField(blank=True, max_length=255)),
                ('github', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='team/pyconcz2017/')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
